### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TSGames** [rouralberto/simple-ots#1]
Hi,

I would like to fork this repo and customize some things, may also creating a ready to use docker image.

Unfortunately,  there is no license attached. Would it be possible to add one? Thanks!

**Comment by rouralberto** [comment]
Sorry for the late reply! It's Apache 2.0 (I just added it)

About the Docker Image, there is already an available one to use in Dockerhub ([roura/simple-ots](https://hub.docker.com/r/roura/simple-ots))
